version: '3'

services:
  app:
    build: ..
    expose:
      - 8000
    volumes:
      - .:/app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/app
    depends_on:
      - app